FROM python:3.11-slim

ENV PYTHONBUFFERED=1\
DATABASE_URL='sqlite:///./test.db'

WORKDIR /backend

COPY requirements.txt .

RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt

# Copy the application code from backend 
COPY  . .

EXPOSE 8000

CMD [ "uvicorn", "main:app", "--host" ,"0.0.0.0", "--port","8082" ]

